### ISSUE TITLE
Container build is not published

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/docker-publish-worker#6]
Looks like builds with containers are not available and packages are not iniside container. See this build
`https://abf.openmandriva.org/build_lists/568761`

Important info from publish logs:
```
creating /share/platforms/cooker/container/568761/x86_64/main/release/.publish.lock
'x86_64' generated an exception: [Errno 17] File exists: '/share/platforms/cooker/container/568761/x86_64/main/release'
```

**Comment by fedya** [comment]
[fixed](https://github.com/OpenMandrivaSoftware/docker-publish-worker/commit/0e242b712cb6a08902bcdfabee515b389af0e5ea)

**Comment by tpgxyz** [comment]
Thanks
